/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SettingsShortcutsRouteImport } from './routes/settings.shortcuts'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMemoryRouteImport } from './routes/settings.memory'
import { Route as SettingsDangerRouteImport } from './routes/settings.danger'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDangerRoute = SettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shortcuts': typeof ShortcutsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/share/$token': typeof ShareTokenRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shortcuts': typeof ShortcutsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/share/$token': typeof ShareTokenRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shortcuts': typeof ShortcutsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/share/$token': typeof ShareTokenRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/changelog'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/shortcuts'
    | '/signup'
    | '/terms'
    | '/usage'
    | '/checkout/return'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/memory'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/share/$token'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/changelog'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/shortcuts'
    | '/signup'
    | '/terms'
    | '/usage'
    | '/checkout/return'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/memory'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/share/$token'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/changelog'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/shortcuts'
    | '/signup'
    | '/terms'
    | '/usage'
    | '/checkout/return'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/memory'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/share/$token'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ChangelogRoute: typeof ChangelogRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShortcutsRoute: typeof ShortcutsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UsageRoute: typeof UsageRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger': {
      id: '/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof SettingsDangerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsDangerRoute: typeof SettingsDangerRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsDangerRoute: SettingsDangerRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ChangelogRoute: ChangelogRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShortcutsRoute: ShortcutsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UsageRoute: UsageRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
